server:
  port: 8080
  servlet:
    contextPath: /books-webservice
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: books-webservice

api:
  google-books:
    url: ${GOOGLE_BOOKS_API_URL:https://www.googleapis.com/books/v1}
    key: ${GOOGLE_API_KEY:AIzaSyBwl9d0iDEIdQf39TsXA50gNchIr_R33Qg}